ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "pendingPlan" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "planChangeEffectiveAt" TIMESTAMP(3);

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "cancelAtPeriodEnd"
BOOLEAN NOT NULL DEFAULT false;